### ISSUE TITLE
Add AOS

### ISSUE THREAD

**Issue by mepda** [mepda/nuxt-deluxe-starter#3]
Add the AOS library to our project and then animate some of the different parts of the page

**Comment by saraogipraveen** [comment]
@mepda I am taking this up, Please assign

**Comment by saraogipraveen** [comment]
Also add "hactoberfest" topic to the repository 
![image](https://user-images.githubusercontent.com/16433473/97167068-396a1780-17ac-11eb-8dd2-9068a66fb9e3.png)

**Comment by mepda** [comment]
This is close -- please have the AOS library in a plugin called in the nuxt.config also so it can be globally accessed (not just initiated on each component)

**Comment by saraogipraveen** [comment]
> This is close -- please have the AOS library in a plugin called in the nuxt.config also so it can be globally accessed (not just initiated on each component)

@mepda Done, please check
